### ISSUE TITLE
Cannot connect to Gitlab due to cert validation even though it's set to ignore

### ISSUE THREAD

**Issue by parvezakkas** [gmessner/gitlab4j-api#80]
Hi,

I'm new to this repository but it looks interesting. I wrote a small groovy class to try this out. But, I'm getting SSLHandshake error even though I set the option to ignore ssl certificate when I try it out. Not sure where I made a mistake. Here's my class that only has one method called `getBranch`. Calling this method returns the following error (small section of the stacktrace here):

```
org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:326)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:67)
        at org.gitlab4j.api.RepositoryApi.getBranch(RepositoryApi.java:89)

```

My Class

```groovy
package org.test.gitlab

import org.gitlab4j.api.GitLabApi
import org.gitlab4j.api.RepositoryApi
import org.gitlab4j.api.models.Branch

class MyGitlab {
    GitLabApi gitlab

    MyGitlab(String gitlabUrl, String gitlabToken) {
        GitLabApi gitlabApi = new GitLabApi(gitlabUrl, gitlabToken)
        this.gitlab = gitlabApi
        gitlab.setIgnoreCerificateErrors(true)
    }
    //get a branch
    Branch getBranch(Integer projectId, String branchName) {
            return gitlab.getRepositoryApi().getBranch(projectId, branchName)
    }
 }
```

Also, note that you have a typo on the method name. Currently you have `setIgnoreCerificateErrors`. You're missing a "t". It should be `setIgnoreCertificateErrors`

**Comment by gmessner** [comment]
@parvezakkas 
Which version of GitLab4J-API are you using?

**Comment by parvezakkas** [comment]
I'm using version 4.5.0

**Comment by gmessner** [comment]
@parvezakkas 
I have fixed the name typo and have updated the logic to work correctly with Java 7+ and Jersey 2.0+.  

I do not have a setup where I can test with an invalid certificate, if you are able to do that and respond with your results I would appreciate it.

**Comment by parvezakkas** [comment]
@gmessner - Thanks for the update. I just tried it and it didn't work. I think I'm not getting the updated build artifact of this project. I tried both "4.5.0" and the latest version:

```
dependencies {
    compile localGroovy()
    compile 'org.gitlab4j:gitlab4j-api:+'
}
```

I'm still getting same error as before. When I tried to use the **new** command, `setIgnoreCertificateErrors(true)`, I'm getting a `MissingMethodException`

```
groovy.lang.MissingMethodException: No signature of method: org.gitlab4j.api.GitLabApi.setIgnoreCertificateErrors() is applicable for argument types: (java.lang.Boolean) values: [true]
    Possible solutions: setIgnoreCerificateErrors(boolean), getIgnoreCertificateErrors()
```

**Comment by gmessner** [comment]
@parvezakkas 
Sometimes it takes a day or so to propagate a new version.  The new version is 4.6.0

**Comment by gmessner** [comment]
@parvezakkas
Have you had a chance to test the new version (4.6.0)?

**Comment by parvezakkas** [comment]
@gmessner Yes, I tried it today. Now I'm able to connect to my private Gitlab instance `setIgnoreCertificateErrors` enabled. I was also able to create new branch and tag using this library. 

Thanks a lot for the quick response.

**Comment by gmessner** [comment]
Glad to be of assistance and thank you for testing it.

**Comment by fooller** [comment]
I use password to login, throw the same Exception, and I set setIgnoreCertificateErrors false
